---
title: "Visualization"
format: html
editor: visual
---

```{r}
# data management, processing, visualization
library(tidyverse) # for data manipulation
library(tidymodels)
library(stars) # for raster data
library(sf) # for spatial data
library(rnaturalearth) # for world map data
library(terra)
library(here)
source(here('R/helpers.R'))
library(scico)
library(bundle)
```

# Testing on Oaxaca predictions

```{r}
mexico_predictors <- readRDS(here('data/derived/mexico_predictors.rds'))[[-4]] # removes sediment

bart_final <- readRDS(here('outputs/models/bart_final.rds')) |>
  unbundle()
```


```{r}
set.seed(42)
mexico_predictions <- predict(mexico_predictors, 
                               bart_final, 
                               na.rm = TRUE
                              ) |>
  st_as_stars() |>
  inverse_logit_transform()
plot(mexico_predictions2, downsample = 0)
```

```{r}
ggplot() +
  geom_stars(data = (mexico_predictions)) +
  geom_sf() +
  scale_fill_viridis_c(option = 'magma', na.value = NA) +
  theme_bw()
```

full global range of median bedrock model .703629 to .755891 q3 is .701232, .805516 q1 .700216, .755891

```{r}
bedrock_model_median <- read_stars(here('data/raw/isotope_predictors/rm1_reproj.tif')) |>
  st_set_crs(st_crs(mexico_predictions)) |>
  st_crop(mexico_predictions)

bedrock_model_q3 <- read_stars(here('data/raw/isotope_predictors/srsrq3.tif')) |>
  st_set_crs(st_crs(mexico_predictions)) |>
  st_crop(mexico_predictions)

plot(bedrock_model_median, downsample = 0)

bed_med <- bedrock_model_median |>
  as_tibble()
rast(here('data/raw/isotope_predictors/rm1_reproj.tif')) |> range()
rast(here('data/raw/isotope_predictors/srsrq1.tif')) |> range()

bed_med
st_crs(mexico_predictions)
```

```{r}
ggplot() +
  geom_stars(data = merge(c(mexico_predictions, mexico_predictions)) |> setNames('Sr')) +
  coord_sf() +
  facet_wrap(~attributes) +
  scale_fill_viridis_c(option = 'magma', na.value = NA) +
  theme_bw()

ggplot() +
  geom_stars(data = bedrock_model_median) +
   scale_fill_viridis_c(option = 'magma', na.value = NA) +
  theme_bw() +
  coord_sf()

ggplot() +
  geom_stars(data = bedrock_model_q3) +
   scale_fill_viridis_c(option = 'magma', na.value = NA) +
  theme_bw() +
  coord_sf()

ggplot() +
  geom_stars(data = mexico_predictions) +
  coord_sf() +
  scale_fill_viridis_c(option = 'magma', na.value = NA) +
  theme_bw()
```



n.threads isn't argument to internal bart predict function

```{r}
set.seed(42)
mexico_confidence <- predict(mexico_predictors, bart_final, type = 'conf_int',
                              na.rm = TRUE
) |>
  st_as_stars() |>
  inverse_logit_transform()


plot(mexico_confidence, downsample = 0)
plot(mexico_confidence[,,,2, drop = TRUE] - mexico_confidence[,,,1, drop = TRUE], downsample = 0)
```


Final predictions all together.

```{r}
predictions <- c(mexico_predictions, split(mexico_confidence))


saveRDS(predictions, here('data/derived/predictions.rds'))
predictions <- readRDS(here('data/derived/predictions.rds'))
plot(predictions)

ggplot() +
  geom_stars(data = merge(predictions)) +
  scale_fill_viridis_c(na.value = NA) +
  facet_wrap(~attributes) +
  theme_bw()
```


```{r}
#mexico <- ne_countries(scale = 'medium') |>
#  st_transform(eck4) |>
#  st_crop(mexico_bbox)
albers <- '+proj=aea +lon_0=-96 +lat_1=16.5 +lat_2=21.5 +lat_0=19 +datum=WGS84 +units=m +no_defs'
mexico_bbox <- st_bbox(c(xmin = -106, xmax = -87, ymin = 15, ymax = 23), crs = 4326) |>
  st_transform(albers) 
mexico <- ne_states('mexico') |>
  st_transform(albers) |>
  st_crop(mexico_bbox)
#which?
world <- ne_countries() |>
  st_transform(eck4)

#mexico <- st_crop(world, st_bbox(predictions))
oaxaca <- mexico |>
  filter(name == 'Oaxaca') |>
  st_transform(st_crs(predictions))
oaxaca2 <- mexico |>
  filter(name == 'Oaxaca')
```

```{r fig.width=20}
crs_lcc <- "+proj=lcc +lat_1=16 +lat_2=20 +lat_0=18 +lon_0=-95.5 +datum=WGS84 +units=m"
ggplot() +
  geom_stars(data = predictions[1,,]) +
  geom_sf(data = mexico, fill = NA, linewidth = .1, color = 'white') +
  coord_sf(expand = FALSE) +
  scale_fill_scico(palette = 'lipari', na.value = NA, name = expression(""^"87" * "Sr/" * ""^"86" * "Sr")) +
  theme_bw() +
  theme(
    panel.background = element_rect(fill = "lightblue"),
    panel.grid.major = element_line(color = "white", linewidth = 0.5),
        plot.margin = margin(0, 0, 0, 0)
  ) +
  labs(x = '', y = '') + 
  ggspatial::annotation_scale(location = "bl", width_hint = 0.2) +
  ggspatial::annotation_north_arrow(
    location = "bl", 
    which_north = "true",
    pad_x = unit(0.2, "in"), 
    pad_y = unit(0.2, "in"),
    style = ggspatial::north_arrow_fancy_orienteering
  )
```

```{r fig.width=20}
crs_lcc <- "+proj=lcc +lat_1=16 +lat_2=20 +lat_0=18 +lon_0=-95.5 +datum=WGS84 +units=m"
ggplot() +
  geom_stars(data = predictions[1,,] |> st_transform(crs = 32615)) +
  geom_sf(data = mexico |> st_transform(crs = 32615), fill = NA, linewidth = .1, color = 'white') +
  coord_sf(expand = FALSE, crs = 32615) +
  scale_fill_scico(palette = 'lipari', na.value = NA, name = expression(""^"87" * "Sr/" * ""^"86" * "Sr")) +
  theme_bw() +
  theme(
    panel.background = element_rect(fill = "lightblue"),
    panel.grid.major = element_line(color = "white", linewidth = 0.5),
        plot.margin = margin(0, 0, 0, 0)
  ) +
  labs(x = '', y = '') + 
  ggspatial::annotation_scale(location = "bl", width_hint = 0.2) +
  ggspatial::annotation_north_arrow(
    location = "bl", 
    which_north = "true",
    pad_x = unit(0.2, "in"), 
    pad_y = unit(0.2, "in"),
    style = ggspatial::north_arrow_fancy_orienteering
  )
```

```{r fig.width=20, fig.asp = .45}
ggplot() +
  geom_stars(data = predictions[1,,]) +
  geom_sf(data = mexico, fill = NA, linewidth = .1, color = 'white') +
  coord_sf(expand = FALSE) +
  scale_fill_scico(palette = 'lipari', na.value = NA, name = expression(""^"87" * "Sr/" * ""^"86" * "Sr")) +
  theme_bw() +
  theme(
    panel.background = element_rect(fill = "lightblue"),
    panel.grid.major = element_line(color = "white", linewidth = 0.5),
        plot.margin = margin(0, 0, 0, 0)
  ) +
  labs(x = '', y = '') + 
  ggspatial::annotation_scale(location = "bl", width_hint = 0.2) +
  ggspatial::annotation_north_arrow(
    location = "bl", 
    which_north = "true",
    pad_x = unit(0.2, "in"), 
    pad_y = unit(0.2, "in"),
    style = ggspatial::north_arrow_fancy_orienteering
  )

ggsave(here('outputs/figures/mesoamerica_iscoscape_v5.png'), width = 10, height = 6.4)
```

```{r fig.width=20, fig.asp = .45}
ggplot() +
  geom_stars(data = (predictions[3,,, drop = TRUE] - predictions[2,,, drop = TRUE]) |> setNames('CI')) +
  geom_sf(data = mexico, fill = NA, linewidth = .1, color = 'white') +
  coord_sf(expand = FALSE) +
  scale_fill_scico(palette = 'turku', na.value = NA, name = expression("CI ("^"87" * "Sr/" * ""^"86" * "Sr" * ")")) +
  theme_bw() +
  theme(
    panel.background = element_rect(fill = "lightblue"),
    panel.grid.major = element_line(color = "white", linewidth = 0.5),
        plot.margin = margin(0, 0, 0, 0)
  ) +
  labs(x = '', y = '') + 
  ggspatial::annotation_scale(location = "bl", width_hint = 0.2) +
  ggspatial::annotation_north_arrow(
    location = "bl", 
    which_north = "true",
    pad_x = unit(0.2, "in"), 
    pad_y = unit(0.2, "in"),
    style = ggspatial::north_arrow_fancy_orienteering
  )

ggsave(here('outputs/figures/mesoamerica_iscoscape_uncertainty_v5.png'), width = 10, height = 6.4)
```

```{r fig.width=10, fig.asp =.9}
ggplot() +
  geom_stars(data = merge(predictions[2:3, , , .drop = TRUE] |> setNames(c('Lower', 'Upper')))) +
  geom_sf(data = mexico, fill = NA, linewidth = .1, color = 'white') +
  coord_sf(expand = FALSE) +
  scale_fill_scico(palette = 'lipari', na.value = NA, name = expression(""^"87" * "Sr/" * ""^"86" * "Sr")) +
  theme_bw() +
  theme(
    panel.background = element_rect(fill = "lightblue"),
    panel.grid.major = element_line(color = "white", linewidth = 0.5),
        plot.margin = margin(0, 0, 0, 0)) +
  labs(x = '', y = '') + 
  facet_wrap(~attributes, nrow = 2) +
  ggspatial::annotation_scale(location = "bl", width_hint = 0.2) +
  ggspatial::annotation_north_arrow(
    location = "bl", 
    which_north = "true",
    pad_x = unit(0.2, "in"), 
    pad_y = unit(0.2, "in"),
    style = ggspatial::north_arrow_fancy_orienteering
  )

ggsave(here('outputs/figures/mesoamerica_iscoscape_range_v5.png'), width = 10, height = 10)
```

```{r fig.width=10}
ggplot() +
  geom_sf(data = mexico |> st_crop(oaxaca2 |> st_buffer(20000)), fill = 'lightgrey', color = NA) +
  geom_stars(data = st_crop(predictions[1,,], st_bbox(oaxaca |> st_buffer(20000))) |> setNames('Sr'), alpha = 0.5) +
  geom_stars(data = st_crop(predictions[1,,], oaxaca)|> setNames('Sr')) +
    geom_sf(data = oaxaca, fill = NA, linewidth = 1, color = 'white') +
  geom_sf(data = filter(dat, oaxaca) |> st_transform(albers), color = 'white') +
    geom_sf(data = dat |> filter(type == 'human') |> st_transform(albers) |> st_filter(oaxaca2), color = 'red') +
  coord_sf(expand = FALSE) +
  scale_fill_scico(palette = 'lipari', na.value = NA, name = expression(""^"87" * "Sr/" * ""^"86" * "Sr")) +
  theme_bw() +
  theme(
    panel.background = element_rect(fill = "lightblue"),
    panel.grid.major = element_line(color = "white", linewidth = 0.5),
        plot.margin = margin(0, 0, 0, 0)
  ) +
  labs(x = '', y = '') + 
  ggspatial::annotation_scale(location = "bl", width_hint = 0.2) +
  ggspatial::annotation_north_arrow(
    location = "bl", 
    which_north = "true",
    pad_x = unit(0.2, "in"), 
    pad_y = unit(0.2, "in"),
    style = ggspatial::north_arrow_fancy_orienteering
  )

ggsave(here('outputs/figures/oaxaca_isoscape_bart_v5.png'), width = 10, height = 6.4)
```






## Origin Assignment Monte Alban

```{r}
predictions <- readRDS(here('data/derived/predictions.rds')) |> 
  st_crop(oaxaca)
plot(predictions)
plot(predictions[,,,2, drop = TRUE])
oaxaca_predictors <- st_crop(st_as_stars(mexico_predictors), st_bbox(oaxaca)) |> split()

plot(oaxaca_predictors)

montealban <- test |>
  filter(type2 == 'Zapotec') %>%
  bake(extract_recipe(bart_final), .)


predict_bart <- getS3method("predict", "bart", envir = asNamespace("dbarts"))
library(dbarts)

predict_bart(extract_fit_engine(bart_final), montealban, type = 'ppd') |> 
  inverse_logit_transform() |>
  as_tibble() |>
    pivot_longer(everything()) |>
  ggplot() +
  geom_histogram(aes(value)) +
  scale_y_continuous(labels=function(x)x/8000) +
 # geom_vline(xintercept = inverse_logit_transform(filter(test, type2 == 'Zapotec')$Sr), color = 'black') +
#  geom_vline(xintercept = c(0.70664, 0.70699), color = 'red') +
  labs(x = '87Sr/86Sr', y = 'Density') +
  theme_bw()
 
ggsave(here('outputs/figures/montealban_density.png'), width = 6, height =5, bg = 'white')
   geom_histogram(data = tibble(test = rnorm(1000, 0.70664, 0.0007)), aes(test), color = 'red', alpha = 0.5) +
    geom_histogram(data = tibble(test = rnorm(1000, 0.70699, 0.0007)), aes(test), color = 'red', alpha = 0.5)

predict_bart(extract_fit_engine(bart_final), montealban, type = 'ppd') |> 
  inverse_logit_transform() |>
  as_tibble() |>
    pivot_longer(everything()) |>
  ggplot() +
  geom_density(aes(value), fill = 'darkgrey') +
  #geom_vline(xintercept = filter(test, type2 == 'Zapotec')$Sr |> inverse_logit_transform(), color = 'red') +
  #geom_vline(xintercept = c(0.70664, 0.70699)) +
  theme_bw() +
  labs(x ='87Sr/86Sr', y = 'Density')

predict_bart(extract_fit_engine(bart_final), montealban, type = 'ppd') |> 
  inverse_logit_transform() |>
  as_tibble() |>
  ggplot(aes(V1)) +
  geom_histogram() +
  geom_vline(xintercept = filter(test, type2 == 'Zapotec')$Sr |> inverse_logit_transform(), color = 'red')
quantile(montealban$Sr |> inverse_logit_transform())

predict(extract_fit_engine(bart_final), montealban, type = 'ppd') |> 
  inverse_logit_transform() |>
quantile(c(0.025, 0.05, 0.95, 0.975))
```


```{r}
# Read and process the data (keeping your original data processing)
ma_samp <- readxl::read_excel(here('Monte_Alban_Test_Individuals.xlsx')) |>
  select(entry_id = `Entry ID`,
         burial_id = `Burial ID Number`,
         Sr = `87Sr/86Sr`,
         sd = `± error...44`,
         local = `Sr Local/non-local`,
         type = `Sample Type/Element`) |>
  # Remove the simulation step - work with raw analytical data
  distinct()  |> # Remove any duplicates from the unnesting
  mutate(actual_se = sd * Sr, # convert % SE to actual SE
         type = factor(type, levels = c('femur', 'enamel'))) 


# Get model prediction ranges (keeping your quantile approach)
set.seed(42)
model_range <- predict_bart(extract_fit_engine(bart_final), montealban, type = 'ppd') |> 
  inverse_logit_transform() |>
  as_tibble() |>
  pivot_longer(everything()) |>
  pull(value) |>
  quantile(c(0.25, 0.4, 0.5, 0.6, 0.75))

# Create the plot with error bars instead of boxplots
ggplot(ma_samp, aes(x = burial_id, y = Sr, color = type)) +
  # Gray prediction range (your existing approach)
  annotate("rect", 
           xmin = -Inf, xmax = Inf,
           ymin = model_range[1], ymax = model_range[5], 
           alpha = 0.3, fill = "gray") +
  # annotate("rect", 
   #        xmin = -Inf, xmax = Inf,
    #       ymin = model_range[2], ymax = model_range[4], 
     #      alpha = 0.3, fill = "gray") +
  geom_hline(yintercept = model_range[3], linetype = 2, linewidth = 1, color = 'darkgrey') +
  
  # Add points for measured values
  geom_point(size = 4, position = position_dodge(width = 0.3)) +
  
  # Add error bars (±1 SE)
  geom_errorbar(aes(ymin = Sr - actual_se, ymax = Sr + actual_se), 
                width = 0.2, 
                position = position_dodge(width = 0.3),
                linewidth = 1) +
  
  # Optional: Add error bars for ±2 SE as thinner lines
  geom_errorbar(aes(ymin = Sr - 2*actual_se, ymax = Sr + 2*actual_se), 
                width = 0.1, 
                position = position_dodge(width = 0.3),
                linewidth = 0.5, alpha = 0.6) +
  
  coord_flip() +
  scale_x_discrete(limits = rev) +
  scale_color_manual(name = '', values = c("enamel" = "#E69F00", "femur" = "#56B4E9")) +
  theme_bw() +
  theme(
    panel.grid.minor = element_blank(),
    legend.position = "right"
  ) +
  labs(y = expression(""^"87" * "Sr/" * ""^"86" * "Sr"), x = 'Burial ID')

ggsave(here('outputs/figures/montealban_locals_error_bars_2_se_v7.png'), width = 6, height = 4, bg = 'white')
```


```{r}
library(philentropy)

ma_dens <- predict(extract_fit_engine(bart_final), montealban, type = 'ppd') |> 
  inverse_logit_transform() |>
  as_tibble() |>
  pull(V1) |>
  binned.kernel.est(range.data = c(.704, .715)) |>
  as_tibble()
  
ggplot(ma_dens) +
  geom_line(aes(x = x, y = y))

purp <- as_tibble(oaxaca_predictors) %>%
  mutate(type = factor('human', levels = levels(train$type))) %>%
  remove_missing() %>%
  bake(extract_recipe(bart_final), .) %>%
  predict(extract_fit_engine(bart_final), ., type = 'ppd', n.threads = 6)

pop <- map(1:ncol(purp), ~binned.kernel.est(inverse_logit_transform(purp[,.x]), range.data = c(.704, .715))$y)

probs <- do.call(rbind, pop) 
row_sums <- rowSums(probs)

prob_norm <- sweep(probs, 1, row_sums, "/")


huck <- dist_one_many(zapsmall(ma_dens$y / sum(ma_dens$y)), zapsmall(prob_norm), method = 'jensen-shannon', unit = 'log2')

hist(huck)
prob_rast <- oaxaca_predictors |>
  #rowwise() %>%
  #mutate(all_complete = !any(is.na(c_across(everything())))) %>%
  #ungroup()
 # transmute(test = any(is.na(everything())))
  select(soil_clay_cec_gradient) |>
  transmute(prob = replace(soil_clay_cec_gradient, !is.na(soil_clay_cec_gradient), huck))

ggplot() +
 geom_stars(data = 1 - sqrt(prob_rast)) +
 # geom_stars(data = 1 - (prob_rast / 2)) +
  geom_sf(data = oaxaca2, fill = NA, color = 'white') +
  geom_sf(data =  test |>
  filter(type2 == 'Zapotec'), fill = NA, color = 'red') +
  scale_fill_viridis_c(na.value = NA) +
  theme_bw()
```

```{r}
mns <- colMeans(purp)
sds <- apply(purp, 2, sd)

herp <- test |>
  filter(type2 == 'Zapotec') |>
  pull(Sr) %>% 
  .[[1]] |>
  dnorm(mns, sds)

herp
prob_rast2 <- oaxaca_predictors |>
  select(soil_clay_cec_gradient) |>
  transmute(prob = replace(soil_clay_cec_gradient, !is.na(soil_clay_cec_gradient), herp))


herp2 <- test |>
  filter(type2 == 'Zapotec') |>
  pull(Sr) %>% 
  .[[8]] |>
  dnorm(mns, sds)

prob_rast3 <- oaxaca_predictors |>
  select(soil_clay_cec_gradient) |>
  transmute(prob = replace(soil_clay_cec_gradient, !is.na(soil_clay_cec_gradient), herp2))


ggplot() +
 geom_stars(data = prob_rast2 / sum(prob_rast2$prob, na.rm = TRUE)) +
 # geom_stars(data = 1 - (prob_rast / 2)) +
  geom_sf(data = oaxaca2, fill = NA, color = 'white') +
  geom_sf(data =  test |>
  filter(type2 == 'Zapotec'), fill = NA, color = 'red') +
  scale_fill_viridis_c(na.value = NA) +
  theme_bw()

ggplot() +
 geom_stars(data = prob_rast3 / sum(prob_rast3$prob, na.rm = TRUE)) +
 # geom_stars(data = 1 - (prob_rast / 2)) +
  geom_sf(data = oaxaca2, fill = NA, color = 'white') +
  geom_sf(data =  test |>
  filter(type2 == 'Zapotec'), fill = NA, color = 'red') +
  scale_fill_viridis_c(na.value = NA) +
  theme_bw()
```

# figs 2 and 1 from manuscript

## Geological Map

```{r, fig.width = 15}
bedrock1 <- read_sf(here('data/archive/G02042022203359X/Litologia_E14_9.shp'))
bedrock2 <- read_sf(here('data/archive/J02042022204037E/Litologia_E14_12.shp'))


oaxaca_city <- st_sf(
  geometry = st_sfc(st_point(c(-96.7266, 17.0732))),
  crs = 4326
) |>
  st_transform(st_crs(bedrock1)) |>
  mutate(name = 'Oaxaca City')

plant_pts <- oaxaca_plants |>
  group_by(Locality) |>
  summarize() |>
  st_transform(st_crs(bedrock1)) |>
  rename(name = Locality) |>
  bind_rows(oaxaca_city)

points <- montealban |>
  slice(1) |>
  select(geometry) |>
  mutate(name = 'Monte Alban') |>
  st_as_sf() |>
  st_transform(st_crs(bedrock1)) |>
  bind_rows(oaxaca_city)

library(ggrepel)

bedrock <- rbind(bedrock1, bedrock2) %>%
  st_union(by_feature = TRUE) |>
  st_crop(st_buffer(plant_pts, 10000)) |>
  group_by(EDFINAL) |>
  summarize() |>
  mutate(
    period_en = case_when(
      EDFINAL %in% c("Berriasiano", "Cretácico inferior") ~ "Lower Cretaceous",
      EDFINAL == "Proterozoico medio" ~ "Mesoproterozoic",
      EDFINAL == "Pérmico" ~ "Permian", 
      EDFINAL == "Aptiano" ~ "Aptian",
      EDFINAL == "Cenomaniano" ~ "Cenomanian", 
      EDFINAL == "Jurásico medio" ~ "Middle Jurassic",
      EDFINAL == "Maastrichtiano" ~ "Maastrichtian",
      EDFINAL == "Eoceno" ~ "Eocene",
      EDFINAL == "Mioceno" ~ "Miocene",
      EDFINAL == "Plioceno" ~ "Pliocene",
      EDFINAL == "Holoceno" ~ "Holocene"
    ),
    # Create factor with chronological levels (oldest to youngest)
    period_en = factor(period_en, levels = c(
      "Mesoproterozoic", "Permian", "Middle Jurassic", "Lower Cretaceous",
      "Aptian", "Cenomanian", "Maastrichtian", "Eocene", "Miocene", 
      "Pliocene", "Holocene"
    ))
  )


ggplot() +
  geom_sf(data = bedrock, aes(fill = period_en), color = "white", size = 0.1) +
  scale_fill_brewer(palette = 'Spectral', name = 'Geologic Age', direction = -1) +
  geom_sf(data = plant_pts, color = 'black') +
   geom_label_repel(
    data = plant_pts,
    aes(geometry = geometry, label = name),
    stat = "sf_coordinates",
    segment.color = "black",
     force = 2,              # Higher = more repulsion (default is 1)
    min.segment.length = 0, # Always show connector lines
    nudge_x = 0.2,          # Push right
    nudge_y = 0.2,          # Push up
    # Control repulsion distance
    force_pull = 2,         # Pull towards nudge direction
    max.overlaps = Inf      # Allow all labels to show
  ) +
  theme_minimal() +
  labs(x = '', y = '')


```

```{r, fig.width = 15}
library(dplyr)
library(ggplot2)
library(ggnewscale)
library(RColorBrewer)
library(ggrepel)
library(ggtext)

# Assign eras
bedrock <- bedrock %>%
  mutate(
    era = case_when(
      period_en %in% c("Mesoproterozoic") ~ "Precambrian",
      period_en %in% c("Permian") ~ "Paleozoic",
      period_en %in% c("Middle Jurassic","Lower Cretaceous","Aptian","Cenomanian","Maastrichtian") ~ "Mesozoic",
      period_en %in% c("Eocene","Miocene","Pliocene","Holocene") ~ "Cenozoic",
      TRUE ~ NA_character_
    )
  )

# --- groups by era ---
groups <- list(
  Precambrian = c("Mesoproterozoic"),
  Paleozoic   = c("Permian"),
  Mesozoic    = c("Middle Jurassic","Lower Cretaceous","Aptian","Cenomanian","Maastrichtian"),
  Cenozoic    = c("Eocene","Miocene","Pliocene","Holocene")
)

# make sure period_en is a factor with your desired order (you already set this earlier)
# build a single, named color map used by every sub-legend
all_lvls <- levels(bedrock$period_en)
# reverse Spectral to roughly match direction = -1 in scale_fill_brewer
pal <- rev(brewer.pal(length(all_lvls), "Spectral"))
cols_all <- setNames(pal, all_lvls)

p <- ggplot() +
  # Precambrian
  geom_sf(data = dplyr::filter(bedrock, period_en %in% groups$Precambrian),
          aes(fill = period_en), color = "white", size = 0.1) +
  scale_fill_manual(
    values = cols_all[groups$Precambrian],
    name = "Precambrian",
    guide = guide_legend(order = 1)
  ) +
  new_scale_fill() +

  # Paleozoic
  geom_sf(data = dplyr::filter(bedrock, period_en %in% groups$Paleozoic),
          aes(fill = period_en), color = "white", size = 0.1) +
  scale_fill_manual(
    values = cols_all[groups$Paleozoic],
    name = "Paleozoic",
    guide = guide_legend(order = 2)
  ) +
  new_scale_fill() +

  # Mesozoic
  geom_sf(data = dplyr::filter(bedrock, period_en %in% groups$Mesozoic),
          aes(fill = period_en), color = "white", size = 0.1) +
  scale_fill_manual(
    values = cols_all[groups$Mesozoic],
    name = "Mesozoic",
    guide = guide_legend(order = 3)
  ) +
  new_scale_fill() +

  # Cenozoic
  geom_sf(data = dplyr::filter(bedrock, period_en %in% groups$Cenozoic),
          aes(fill = period_en), color = "white", size = 0.1) +
  scale_fill_manual(
    values = cols_all[groups$Cenozoic],
    name = "Cenozoic",
    guide = guide_legend(order = 4)
  ) +

  # points/labels/theme
  geom_sf(data = plant_pts, color = 'black') +
  geom_label_repel(
    data = plant_pts,
    aes(geometry = geometry, label = name),
    stat = "sf_coordinates",
    segment.color = "black",
    force = 2, min.segment.length = 0,
    nudge_x = 0.2, nudge_y = 0.2,
    force_pull = 2, max.overlaps = Inf
  ) +
  theme_minimal() +
  labs(x = NULL, y = NULL) 

p

```

```{r}
ggsave(here('outputs/figures/geological_map.png'), width = 12, height = 8, bg = 'white')
```

## sentinel map

```{r fig.width = 20}

ggplot() +
  geom_stars(data = st_rgb(s2, maxColorValue = 1L)) + 
  geom_sf(data = plant_pts |> st_transform(4326), color = 'red', size = 3) +
    geom_label_repel(
    data = plant_pts|> st_transform(4326),
    aes(geometry = geometry, label = name),
    stat = "sf_coordinates",
    segment.color = "black",
     force = 2,              # Higher = more repulsion (default is 1)
    min.segment.length = 0, # Always show connector lines
    # Control repulsion distance
    force_pull = 2,         # Pull towards nudge direction
    max.overlaps = Inf      # Allow all labels to show
  ) +
  #scale_size_area(name = 'area (km2)') +
  #coord_sf(crs = st_crs(elev_tiles)) +
  theme_void()
```

```{r}
ggsave(here('outputs/figures/satellite_map.png'), width = 10, height = 10, bg = 'white')
```

```{r}
library(reticulate)
py_require('earthengine-api')
```

```{r}
library(stars)
library(rgee)
ee <- import('ee')

ee$Initialize()

bbox_ee <- sf_as_ee(st_as_sfc(st_bbox(bedrock |> st_buffer(5000))) |> st_transform(4326))

# Visualization parameters
viz <- list(bands = c("B4", "B3", "B2"), min = 0, max = 2500)
```

```{r}

# Get Sentinel-2 data without the problematic preprocess() function
s2 <- ee$ImageCollection("COPERNICUS/S2_SR_HARMONIZED")$
  filterBounds(bbox_ee)$
  filter(ee$Filter$date('2023-01-01', '2023-01-20'))$
 filter(ee$Filter$lt('CLOUDY_PIXEL_PERCENTAGE', 30))$
  select(c('B2', 'B3', 'B4'))$
  median() |>
  ee_as_thumbnail(bbox_ee, dimensions = c(1150, 1080) * 2, vizparams = viz)

image(s2, rgb = c(1, 2, 3), interpolate = TRUE)
```
